my_forum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    # Админка сайта
    path('admin/', admin.site.urls),
    # Раздел редиректа
    path('', RedirectView.as_view(url='posts/'), name='home'),
    # Приложение posts
    path('posts/', include('posts.urls', namespace='posts')),
    # Приложение profiles
    path('profiles/', include('profiles.urls', namespace='profiles')),
    # Создание темы на форуме
    path('create_topic/', include('create_topic.urls', namespace='create_topic')),
    # Показ созданных тем
]

handler404 = 'my_forum.views.handler404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Файл маршрутов приложения posts."""

from django.urls import path
from django.views.generic import TemplateView

from posts.views import create_post, PostDetail, PostList

app_name = 'posts'

urlpatterns = [
    # Главная страница приложения со списком постов
    path(r'', PostList.as_view(), name='post_list'),
    # Страница с детальной информацией о посте
    path(r'<int:pk>/', PostDetail.as_view(), name='post_detail'),
    # Страница с формой для создания нвого поста
    path(r'new/', TemplateView.as_view(template_name='post_create.html'), name='new_post'),
    # API-функция для создания поста
    path(r'create/', create_post, name='create')
]

posts/models.py
"""Модели приложения posts."""

from django.db import models

from posts.utils import get_post_image_upload_path


class Post(models.Model):
    """Модель поста на форуме."""

    title = models.CharField('Заголовок', max_length=256)
    summary = models.TextField('Текст на предпросмотре')
    content = models.TextField('Текст поста')
    published = models.DateTimeField('Дата публикации поста', auto_now_add=True)
    author = models.ForeignKey('auth.User', models.CASCADE, verbose_name='Автор поста', related_name='posts')
    preview_image = models.ImageField('Картинка на посте', upload_to=get_post_image_upload_path, blank=True, null=True)

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        db_table = 'posts'

    def __str__(self):
        return self.title


class Comment(models.Model):
    """Модель комментария к постую"""

    text = models.TextField('Текст комментария', blank=True, null=True)
    author = models.ForeignKey('auth.User', models.CASCADE, verbose_name='Автор комментария', related_name='comments')
    published = models.DateTimeField('Дата публикации', auto_now_add=True)
    to_post = models.ForeignKey('Post', models.CASCADE, verbose_name='Пост', related_name='comments')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        db_table = 'comments'

    def __str__(self):
        return f'Комментарий к посту {self.to_post_id} от {self.author.username}'

posts/views.py
"""Представления для приложения posts."""

from django.shortcuts import redirect
from django.views.generic import DetailView, ListView

from lib.utils import multipart_to_dict
from posts.models import Post


class PostList(ListView):
    """Класс-представление страницы с постами приложения posts."""

    template_name = 'post_list.html'
    queryset = Post.objects.select_related('author').prefetch_related('comments')
    context_object_name = 'posts'


class PostDetail(DetailView):
    """Класс-представление страницы с детальной информацией о посте приложения posts."""

    template_name = 'post_detail.html'
    queryset = Post.objects.select_related('author').prefetch_related('comments')
    context_object_name = 'post'


def create_post(request):
    """
    API-функция для создания нового поста.

    :param request: объект запроса
    :return: редирект на страницу с постами
    """
    response = redirect('posts:post_list')

    if request.method == 'GET':
        return response

    data = multipart_to_dict(request.POST)

    data['preview_image'] = request.FILES.get('preview_image', None)

    data['author'] = request.user

    print(data)

    Post.objects.create(**data)

    return response

posts/templates/post_create.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <title>Форум | Добавить пост</title>
  <link rel="stylesheet" href="{% static 'css/post_create.css' %}" type="text/css">
{% endblock %}

{% block body %}
  {% if user.is_authenticated %}
    <form class="form" method="post" action="{% url 'posts:create' %}" enctype="multipart/form-data">
      {% csrf_token %}

      <span>
        <label for="title">Заголовок</label>
        <input id="title" type="text" name="title" required>
      </span>

      <span>
        <label for="summary">Текст предпросмотра</label>
        <input id="summary" type="text" name="summary" required>
      </span>

      <span>
        <label for="content">Текст статьи</label>
        <input id="content" type="text" name="content" required>
      </span>

      <span>
        <label for="preview_image">Изображение в статье</label>
        <input id="preview_image" type="file" name="preview_image" accept="image/*">
      </span>

      <input type="submit" value="Отправить">
    </form>
  {% else %}
    <p>Вам необходимо авторизоваться, чтобы добавлять посты.</p>
  {% endif %}
{% endblock %}

posts/templates/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/post_detail.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/arrows.css' %}" type="text/css">
  <title>Форум | {{ post.title }}</title>
{% endblock %}

{% block body %}
  <section class="section">
    <h1>{{ post.title }}</h1>

    <p class="content">
      {% if post.preview_image %}
        <img src="{{ post.preview_image.url }}" alt="">
      {% else %}
        <img src="{% static 'img/default-post-image.png' %}" alt="">
      {% endif %}
      <span>{{ post.content }}</span>
    </p>

    <p class="credits">
      {{ post.published }}, {{ post.author.username }}
    </p>

    <a class="go-back" href="{% url 'posts:post_list' %}">
      <div class="arrow left"></div>
      К постам
    </a>

  </section>
{% endblock %}

posts/templates/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/post_list.css' %}" type="text/css">
  <title>Форум</title>
{% endblock %}

{% block body %}
  <section class="section">
    {% for post in posts %}
      <a class="post" href="{% url 'posts:post_detail' post.pk %}">
        {% if post.preview_image %}
          <img src="{{ post.preview_image.url }}" alt="">
        {% else %}
          <img src="{% static 'img/default-post-image.png' %}" alt="">
        {% endif %}

        <div class="post-text">
          <h2>{{ post.title }}</h2>
          <p>{{ post.summary }}</p>
        </div>

        <div class="created-date">
          {{ post.published }}, {{ post.author.get_username }}
        </div>

        <div class="post-comment-count">
          <i class="far fa-comment-alt comment-icon"></i>{{ post.comments.count }}
        </div>

      </a>
    {% empty %}
      <h1>Постов не найдено.</h1>
    {% endfor %}

    {# Только авторизированые пользователи могут добавлять посты #}
    {% if user.is_authenticated %}
      <a href="{% url 'posts:new_post' %}" class="create-post">Создать пост +</a>
    {% endif %}

  </section>
{% endblock %}