create_topic/urls.py
"""Файл маршрутов приложения create_topic."""

from django.conf.urls import url
from django.urls import path

from . import views
from .views import Index, CreatePostPage

app_name = 'create_topic'

urlpatterns = [
    # Главная страница приложения
    path('', Index.as_view(), name='index'),
    path(r'new_post/', CreatePostPage.as_view(), name='creating_posts'),
    path(r'user/<int:pk>/', Index.as_view(), name='user-detail'),
    url('create_post', views.create_post, name='create_post'),
    url('search_post', views.SearchPostsInDB.searching_in_db, name='search_post'),

]

my_forum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    # Админка сайта
    path('admin/', admin.site.urls),
    # Раздел редиректа
    path('', RedirectView.as_view(url='posts/'), name='home'),
    # Приложение posts
    path('posts/', include('posts.urls', namespace='posts')),
    # Приложение profiles
    path('profiles/', include('profiles.urls', namespace='profiles')),
    # Создание темы на форуме
    path('create_topic/', include('create_topic.urls', namespace='create_topic')),
    # Показ созданных тем
]

handler404 = 'my_forum.views.handler404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Файл маршрутов приложения posts."""

from django.urls import path
from django.views.generic import TemplateView

from posts.views import create_post, PostDetail, PostList

app_name = 'posts'

urlpatterns = [
    # Главная страница приложения со списком постов
    path(r'', PostList.as_view(), name='post_list'),
    # Страница с детальной информацией о посте
    path(r'<int:pk>/', PostDetail.as_view(), name='post_detail'),
    # Страница с формой для создания нвого поста
    path(r'new/', TemplateView.as_view(template_name='post_create.html'), name='new_post'),
    # API-функция для создания поста
    path(r'create/', create_post, name='create')
]

create_topic/models.py
"""Модели приложения create_topic."""

from django.db import models


class CreatePost(models.Model):
    """Модель нового поста на форуме."""

    post_user_name = models.CharField(verbose_name='Имя пользователя', default='Не задано имя', max_length=128)
    # нужно будет изменить, когда будет сделана регистрация
    post_name = models.CharField(verbose_name='Тема поста', default='Не задано имя поста', max_length=128)
    # название поста
    post_text = models.TextField(verbose_name='Текст поста', default='Текст не введён')
    # текст поста
    post_time = models.DateTimeField(verbose_name='Дата и время поста', auto_now_add=True)
    # время создания поста

create_topic/views.py
"""Представления для приложения create_topic."""

from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.http.response import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView

from .models import CreatePost


class Index(ListView):
    """Класс-представление основной страницы приложения create_topic."""

    template_name = 'index.html'
    # Ты передавал неправильную модель в шаблон (скопировал ранее у меня видимо)
    # model = User
    model = CreatePost
    # Аналогично с именем, под которым тебе передается в шаблон
    # context_object_name = 'users'
    context_object_name = 'posts'


class CreatePostPage(ListView):
    # класс для создания поста в отдельном окне

    template_name = 'create_post_page.html'
    # путь к шаблону
    model = CreatePost
    # модель информации о посте
    context_object_name = 'posts'


def create_post(request):
    """
    Функция для создания поста.

    :param request: обхект запроса
    """
    text_field = None
    text_post_name = None
    if request.method == 'POST':  # если запрос пост, то
        if 'text_field' in request.POST:
            text_field = request.POST['text_field']  # текст поста
            text_post_name = request.POST['post_name']  # название поста
    if request.method == 'GET':  # присваиваем значение в строке браузера/переменной
        text_field = request.GET['text_field']  # текст поста
        text_post_name = request.GET['post_name']  # название поста
    if text_field and text_post_name is not None:
        create_text = CreatePost(post_text=str(text_field),  # сохраняем в базу
                                 post_name=str(text_post_name))
        create_text.save()
    return HttpResponse('Добавлено!')


def loading_postdb(request):
    """
    Здесь должен быть комментарий.

    :param request:
    :return:
    """
    posts = CreatePost.objects.all()  # загружаем все данные из БД
    return render(request, 'index.html', locals())  # передаём их в html


class SearchPostsInDB:
    """Класс для поиска постов в БД."""

    def __init__(self):
        """Метод-конструктор класса."""
        self.query = None

    def get_text(self, request):
        """Метод для получения значения для фильтрации."""
        self.query = request.GET['search_posts']
        return self.query

    def searching_in_db(self):
        """Метод для поиска в БД."""
        search_query = SearchQuery(self.get_text)
        search_vector = SearchVector(self.get_text)
        search_rank = SearchRank(search_vector, search_query)
        result_searching = CreatePost.objects.annotate(rank=search_rank).order_by('-rank').value_list('text_post_name',
                                                                                                      'text_field')
        return result_searching

create_topic/templates/create_post_page.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/create_post_page.css' %}" type="text/css">

    <title>Создать тему</title>
{% endblock %}


{% block body %}
    <form action="{% url 'create_topic:create_post' %}">
        <table class="main_table">
            <tr>
                <th>
                    <label>
                        <textarea class="topic_name" name="post_name"></textarea>
                    </label>
                </th>
            </tr>
            <tr>
                <td>
                    {% csrf_token %}
                    <label>
                        <textarea class="tinymce" name="text_field"></textarea>

                        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
                        <script type="text/javascript"
                                src="{% static 'plugin/tinymce/tinymce.min.js' %}"></script>
                        <script type="text/javascript"
                                src="{% static 'plugin/tinymce/init-tinymce.js' %}"></script>
                    </label>
                    {% comment %}<input class="text_field" type="text" name="text_field">{% endcomment %}
                    <input type="submit" value="создать пост">
                </td>
            </tr>
        </table>
    </form>
{% endblock %}

create_topic/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  <link rel="stylesheet" href="{% static 'css/index.css' %}" type="text/css">

    <title>Темы</title>
{% endblock %}

{% block body %}
  <form action="{% url 'create_topic:search_post' %}">
    <p>
      <label>
        <input type="search" name="search_posts" placeholder="поиск постов">
        <input type="submit" value="поиск">
      </label>
    </p>
  </form>

  {% for i in posts %}
    <section class="post">
      <div class="post-inside_head">
        <div class="post-item">
          <h1>
            {{ i.post_time }}
          </h1>
            <h2>
                {# Обрати внимание сюда #}
            {{ i.post_name|safe }}
            </h2>
        </div>

          <div class="post-item">
              <h3>
                  <img src="{% static 'img/default-post-image.png' %}" alt="">
            {{ i.post_user_name }}
              </h3>
              <h4 class="text_area" id="posted_text">
                  {# И сюда #}
            {{ i.post_text|safe }}
              </h4>
          </div>
      </div>
    </section>
  {% endfor %}
{% endblock %}

{% block posts %}
  <section class="post">
    <h2>
      something222 {% comment %}почему вот этого не видно, а выше |^| {% endcomment %}
    </h2>
  </section>
{% endblock %}